/** Diagnostic assembly coordinates only; full placement qualification remains blocked. */
export const mechanicalPreviewPlacement = {
  U1: { pcbX: 11, pcbY: -2.3 },
  U2: { pcbX: -9, pcbY: 3 },
  U3: { pcbX: -10, pcbY: -9, layer: "bottom" },
  U4: { pcbX: 0, pcbY: 0 },
  U5: { pcbX: -7.1, pcbY: -8.5, layer: "top" },
  U6: { pcbX: 11, pcbY: -6, layer: "bottom" },
  J_USB: { pcbX: 0, pcbY: -12.1 },
  Q_PD: { pcbX: -10, pcbY: -3, layer: "bottom" },
  D_USB: { pcbX: 6.5, pcbY: -14, layer: "top" },
  D_VBUS: { pcbX: -6.3, pcbY: -12.2, layer: "bottom" },
  L1: { pcbX: -12.6, pcbY: -12 },
  C19: { pcbX: -12, pcbY: 12 },
  C20: { pcbX: 12, pcbY: 12 },
  C1: { pcbX: -1, pcbY: 12 },
  C2: { pcbX: -1, pcbY: 10 },
  C3: { pcbX: -1, pcbY: 8 },
  C4: { pcbX: 2, pcbY: 12 },
  C5: { pcbX: 2, pcbY: 10 },
  C6: { pcbX: 0, pcbY: 5 },
  R1: { pcbX: 2, pcbY: 8, pcbRotation: 180 },
  R2: { pcbX: 4, pcbY: 8 },
  R3: { pcbX: 6, pcbY: 8 },
  C7: { pcbX: 15, pcbY: -5, layer: "bottom" },
  C8: { pcbX: -13, pcbY: -14, layer: "bottom" },
  C9: { pcbX: -15, pcbY: -9, layer: "bottom" },
  C10: { pcbX: 0, pcbY: -7, layer: "bottom" },
  C11: { pcbX: -14, pcbY: -6, layer: "bottom" },
  C12: { pcbX: -14, pcbY: -3, layer: "bottom" },
  C13: { pcbX: -4, pcbY: 4 },
  C14: { pcbX: -4, pcbY: 2 },
  C15: { pcbX: -2, pcbY: 0 },
  C16: { pcbX: -14, pcbY: 5 },
  C17: { pcbX: -14, pcbY: 3 },
  C18: { pcbX: -13, pcbY: -4 },
  R5: { pcbX: -10, pcbY: 8, layer: "bottom" },
  R6: { pcbX: -10, pcbY: 5, layer: "bottom" },
  R4: { pcbX: -4, pcbY: -2, pcbRotation: 180 },
  R7: { pcbX: -8, pcbY: -2, pcbRotation: 180 },
  R8: { pcbX: -14, pcbY: -2 },
  R9: { pcbX: -3, pcbY: -4 },
  R10: { pcbX: -11, pcbY: -7, layer: "top", pcbRotation: 180 },
  R11: { pcbX: -13, pcbY: -6 },
  C21: { pcbX: -2, pcbY: -6 },
  C22: { pcbX: -7, pcbY: -10, layer: "bottom", pcbRotation: 180 },
  C23: { pcbX: 0, pcbY: -12, layer: "bottom" },
  C24: { pcbX: -2.2, pcbY: -12, layer: "bottom" },
  C25: { pcbX: -9, pcbY: -12, layer: "bottom" },
  C26: { pcbX: -7.5, pcbY: -14.5, layer: "bottom" },
  C27: { pcbX: 8, pcbY: -11, layer: "bottom" },
  R12: { pcbX: -6, pcbY: -7, layer: "bottom" },
  R13: { pcbX: -4, pcbY: -7, layer: "bottom" },
  R14: { pcbX: -12, pcbY: 11, layer: "bottom" },
  R15: { pcbX: -12, pcbY: 13, layer: "bottom", pcbRotation: 180 },
  R16: { pcbX: -1, pcbY: -5.5, layer: "bottom", pcbRotation: 180 },
  R17: { pcbX: 2, pcbY: -5.5, layer: "bottom" },
  R18: { pcbX: 4, pcbY: -7, layer: "top" },
} as const

export type BoardViewProps = { mechanicalPreview?: boolean }

export function previewPlacement(
  reference: keyof typeof mechanicalPreviewPlacement,
  mechanicalPreview: boolean,
) {
  return mechanicalPreview ? mechanicalPreviewPlacement[reference] : {}
}
